pedestrian_detector_node:
  ros__parameters:
    attraction_distance: 1.5
    caffemodel_file_adress: /home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/res10_300x300_ssd_iter_140000.caffemodel
    detection_confidence: 0.7
    detection_frequency: 1.0
    enable_vip_recognition: false
    face_database_path: /home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/face/face_data
    prototxt_file_adress: /home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/deploy.prototxt
    vip_recognition_threshold: 0.6
    welcome_message: "欢迎光临"
    enable_initiate_solicitation: false
    enable_active_wake_up: false