##################### ASR 配置 ######################
asr_enable: true # 是否启动激活 ASR 模块
asr_server: ['asr_local'] # 可选值: "asr_local"（本地 jestson orin 设备提供的 ASR 服务） "asr_remote"（远程服务器提供的 ASR 服务 ）
asr_local:
  host: "192.168.10.101" # 本地 ASR 服务器地址，通常是 Jetson Orin 设备的 IP 地址
  port: 6006 # 2002（FunASR 服务端 HTTP 模式）或 6006（sherpa_onnx_asr 服务端 HTTP/WebSocket 模式）
  use_websocket: true # 是否使用 WebSocket ，确保服务端支持 WebSocket
  timeout_sec: 3 # ASR 请求超时时间，单位秒，根据实际情况调整
asr_remote:
  host: "192.168.50.220" # 远程 ASR 服务器地址
  port: 2002
#####################################################

###################### LLM 配置 ######################
llm_enable: true # 是否启动激活 LLM 模块
llm_stream_infer_enable: true # 是否启用 LLM 流式推理，开启后可以配合 tts_stream_infer 实现边说边播效果
llm:
  host: "192.168.50.125"
  port: 8000
  timeout_sec: 5
  temperature: 0.3 # 生成文本的随机程度，范围0-1，值越大越随机
  # （max_tokens + max_completion_tokens(限制模型回复tokens) +RAG 检索结果 tokens) 需要在模型的上下文窗口限制内，例如 2048 或 4096，具体取决于所使用的 LLM 模型
  max_tokens: 200 # 历史消息和生成文本的最大 token 数量，用于控制上下文长度，避免超过模型限制，根据实际情况调整
  max_messages: 10 # 上下文消息数量限制，根据实际情况调整
  max_completion_tokens: 120 # 只限制 生成内容（completion） 的 token 数量，不是输入（prompt）+输出（completion）的总token数，根据实际情况调整

  enable_thinking: false # 是否启用思考过程
  rag_enable: false # 是否启用 RAG 功能，启用后会在 LLM 回复前先进行检索增强
  extra_system_prompt: |
    同时你要根据根据用户的输入，判断用户想要进入哪个状态，并在回答末尾附加。
    可用的状态有：
    CUSTOMER_ENTER: 客户进店（例如：有人在吗）
    NEEDS_GUIDANCE: 需要引导参观（例如：参观一下、带我看看、带我逛逛、想看看等）
    MOVE_TO_WAIT: 退下/不用了（例如：退一下、不用了、退下等）
    WAIT_FOR_TALK: 等待对话（默认状态）
    示例：{
          "instruction": "能带我参观一下吗？",
          "input": "",
          "output": "好的，请跟我这边走<INTENT>NEEDS_GUIDANCE</INTENT>",
          "system": ""
        }
    如果不确定，则输出WAIT_FOR_TALK状态
    
  # 系统提示语，用于指导 LLM 的行为和回复风格，根据实际需求编写
#####################################################

###################### TTS 配置 ######################
tts_enable: false # 是否启动激活 TTS 模块
tts_server: ['tts_local'] # 可选值: "tts_local"（本地 jestson orin 设备提供的 TTS 服务） "tts_remote"（远程服务器提供的 TTS 服务 ）
tts_local:
  host: "192.168.10.101" # 本地 TTS 服务器地址，通常是 Jetson Orin 设备的 IP 地址
  port: 50000
  speaker_id: 0
  speed: 1
  use_websocket: true # 是否使用 WebSocket 连接 TTS 服务器，确保服务器支持 WebSocket
  timeout_sec: 5 # TTS 请求超时时间，单位秒，根据实际情况调整
  playback_start_delay_sec: 0.5 # 起播确认延迟时间，单位秒，根据实际情况调整，影响 tts_active_topic 发布时机

tts_remote:
  host: "192.168.50.220" # 远程 TTS 服务器地址
  port: 50000
  voice_type: "longshu_zh" # 可选值: "default"(女性活泼), "zh"(男性非标准) , "hard_zh"(男性业余), "longshu_zh"(男性专业), "longwan_zh"（女性专业）
#######################################################


################# 音频采集参数 #################
Audio:
  rate: 16000 # 8000 ，16000， 32000， 48000 # 采样率（Hz）每秒多少个采样点（帧）
  channels: 1 # 单声道
  chunk_duration_ms: 20  # 每次读取的音频块持续时间（毫秒）10,20,30
  # chunk_size: 960  # int(rate * chunk_duration_ms / 1000) * 2 # 每次读取的音频块大小（帧数）
  max_file_count: 20  # 最大保存音频文件数量，超过后循环覆盖
################################################

################# VAD 配置 ####################
VAD:
  output_dir: "output" # VAD 结果保存目录
  mode : 2 # 0：最宽松，允许更多非语音通过  1：平衡模式 2：较严格，减少非语音通过  3：最严格，过滤更多非语音
  no_speech_threshold: 0.5 # 静音持续多长时间后认为一句话结束 (秒)
  # reactive_kws_threshold: 100  # 重置唤醒词检测 激活 LLM 时间间隔 (秒) 
  decibel_threshold: -35 # 分贝阈值，低于此值认为是静音 (dB)
  min_recording_duration: 0.4 # 最短有效录音时长 (秒)
  max_recording_duration: 10 # 最大有效录音时长 (秒)
  pause_duration: 4 # 距离上次语音保存多长时间后，允许再次保存音频 (秒)
################################################

################# 唤醒词检测配置 #################
KWS:
  enable: true # 是否启用唤醒词检测
  failed_kws_counts : 1 # 连续未检测到唤醒词次数达到此值时，推送提示语音
  failed_kws_threshold: 30 # 连续未检测到唤醒词次数 达到 failed_kws_counts 后，推送提示语音的时间间隔 (秒)
  reactive_kws_threshold: 100 # 重置 需要唤醒词检测 激活 LLM 时间间隔 (秒) 
  wake_word: "你好小特"
  fuzzy_similarity_threshold: 0.78 # 唤醒词模糊匹配相似度阈值，范围0-1，值越大越严格
################################################

################ ROS 话题配置 ################
ros_cfg:
  asr_publish_topic: "asr_result" # 识别结果发布主题
  llm_publish_topic: "llm_result"   # LLM 回复结果发布主题
  response_publish_topic: "assistant_response" # 综合响应结果话题,同时包含ASR,LLM结果

  tts_active_topic: "sound_detected_default" # TTS 播放状态话题

  user_id_subscribe_topic: "user_id" # 用户ID订阅话题
  user_id_stale_timeout_sec: 3 # 用户ID过期时间，超过此时间未更新则认为用户离开，回退为 None (秒)
##############################################

enable_replace_special_characters: false # 是否启用替换特殊字符功能
enable_interrupt_tts: true # 是否启用打断 TTS 功能
energy_instability_check: false # 是否启用能量不稳定性检测
energy_frames: 50  # 能量窗口最大帧数 (内部使用)  50 x 0.1s = 5s
energy_instability_threshold: 2.5  # 能量不稳定性阈值，超过此值认为多人说话