# Default initial positions for ymbot_xiaoxue_description's ros2_control fake system

initial_positions:
  Neck_Joint1: 0
  Neck_Joint2: 0
  Body_Joint1: 0
  Body_Joint2: 0
  Left_Arm_Joint1: 0
  Left_Arm_Joint2: 0
  Left_Arm_Joint3: 0
  Left_Arm_Joint4: 0
  Left_Arm_Joint5: 0
  Right_Arm_Joint1: 0
  Right_Arm_Joint2: 0
  Right_Arm_Joint3: 0
  Right_Arm_Joint4: 0
  Right_Arm_Joint5: 0