/**:
    ros__parameters:
    video_device: "/dev/video0"  # 使用正确的设备路径
    framerate: 30.0              # 设置为30帧
    io_method: "VIDEOBUFF"
    frame_id: "camera"
    pixel_format: "MJPG"         # 设置为MJPG格式
    image_width: 640             # 选择适当的分辨率
    image_height: 480            # 选择适当的分辨率
    camera_name: "test_camera"
    camera_info_url: ""         # 忽略校准文件警告

    # 摄像头实际支持的参数
    brightness: 60
    contrast: 20
    saturation: 40
    sharpness: 35
    auto_white_balance: false
    white_balance: 6500         # 自定义白平衡温度
    power_line_frequency: 1    # 50Hz

    # 禁用不支持的参数
    autoexposure: true
    autofocus: true
    gain: -1
    focus: -1

