controller_driver:
  ros__parameters:
    bms_info_topic: "robot_device_status" # bms信息话题
    chassis_control_mode_topic: "chassis_vel_control_mode" # 控制模式话题
    cloud_cmd_vel_topic: "cloud_cmd_vel" # cmd_vel话题
    key_cmd_vel_topic: "key_cmd_vel" # chassis_control_mode_topic
    auto_cmd_vel_topic: "cmd_vel" # cmd_vel话题
    en_motor_topic: "en_chassis_motor" # 电机使能话题
    chassis_serial_adress: "/dev/ttyUSB0" # 底盘串口地址
    bms_serial_adress: "/dev/ttyUSB1" # bms串口地址
    chassis_serial_baud_rate: 115200 # 底盘波特率
    bms_sreial_baud_rate: 9600 # bms波特率
    maxMotorSpeed: 400 # 最大电机转速
    minMotorSpeed: -400 # 最小电机转速
    wheel_dis: 0.236 # 轮间距 m
    wheel_radius: 0.085 # 车轮半径 m
    angleDir: 1
    leftDir: 1
    rightDir: -1
    station: 0x01
    write_command: 0x44
    read_command: 0x43
    left_motor_en_addr: 8448
    right_motor_en_addr: 12544
    left_motor_speed_addr: 8984
    right_motor_speed_addr: 13080
    motor_enable: 1
    motor_disable: 0