robot_condition_monitoring:
  ros__parameters:
    robot_state_pub_topic: "robot_condition_monitor/robot_state"
    robot_pose_pub_topic: "robot_condition_monitor/robot_pose"

robot_pose_dot:
  ros__parameters:
    record_robot_pose_topic: "robot_pose_dot/record_robot_pose"
    record_pose_str: "record_pose"
    save_pose_str: "save_pose"
    delete_pose_str: "delete_pose"
    clear_pose_list_str: "clrar_pose_list"
    dot_file_adress: "/home/ymrobot/ros2_ws/src/ceiling/assets/points/special_points.db"
    dot_and_save_str: "record_and_save"
    dot_point_dir: "/home/ymrobot/ros2_ws/src/ceiling/assets/points"
    send_pose_topic_str: "robot_pose_dot/current_robot_pose"
    #ros2 topic pub  --once /robot_pose_dot/record_robot_pose std_msgs/msg/String "{data: "record_pose"}"
    
task_guidance:
  ros__parameters:
    cmd_vel_topic: "cmd_vel"                                    # 机器人速度话题
    task_topic: "task_guidance/task"                            # 任务话题
    task_states_feedback_topic: "task_guidance/task_states"     # 任务状态反馈话题
    is_used_tree: true                                         # 是否使用行为树   -- 好像没用到
    maps_dir: "/home/ymrobot/ros2_ws/src/ceiling/assets/maps"   # 地图文件目录路径
    slam_task_srv_name: "/pgo/pgo_map_slam"                     # SLAM建图
    save_pcd_srv_name: "/pgo/save_maps"                         # SLAM保存地图
    save_pgm_srv_name: "map_management/map_task_manage"         # PCD转PGM
    relocalizer_task_srv_name: "localizer/relocation_map_slam"  # SLAM重定位
    re_pcd_srv_name: "relocalize"                               
    points_db_path: "/home/ymrobot/ros2_ws/src/ceiling/assets/points/special_points.db"  #打点点位保存数据库
    map_db_path: "/home/ymrobot/ros2_ws/src/ceiling/assets/maps/maps.db"                 #地图保存数据库
    timeout: 100 # milliseconds
    dot_point_update_topic: "task_guidance/dot_point_update"                             # 打点点位更新话题 -- 接收
    default_bt_xml_filename: "/home/ymrobot/ros2_ws/src/ceiling/params/behavior_trees/default_bt.xml"  # 默认行为树
    plugin_lib_names:
      - nav2_navigate_to_pose_action_bt_node
      - navigate_through_multiple_poses_node
      - say_something_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - relocation_robot_node
      - get_map_file_node
      - need_index_node
      - get_pose_node
      - get_poses_node
      - check_current_map_node
      - send_init_pose_node
      - load_map_node
      - get_nav_pose_node
      - wait_elevator_node
      - parse_task_node

map_management:
  ros__parameters:
    map_management_srv_name: "map_management/map_task_manage"
    maps_dir: "/home/ymrobot/ros2_ws/src/ceiling/assets/maps"   # 地图文件目录路径
    relcation_action_str: "map_management/relcation_action"   # 发送初始化pose
    re_pcd_srv_name: "/localizer/relocalize"
    load_pgm_map_action_str: "map_management/load_pgm_map"

relocation_node:
  ros__parameters:
    relcation_action_str: "relocation_node/relocation_action"    #重定位action名称
    relocalizer_task_srv_name: "localizer/relocation_map_slam"
    re_pcd_srv_name: "localizer/relocalize"
    maps_dir: "/home/ymrobot/ros2_ws/src/ceiling/assets/maps"

elevator_wait_action:
  ros__parameters:
    wait_elevator_action_name_: "wait_elevator_action"
    elevator_enter_topic_: "wait_elevator_action/enter_elevator"   # 地图文件目录路径
