system_master_control:
  ros__parameters:
    robot_id: "YMZZ202500002"                                                              # 机器人id
    client_id: "YMZZ202500002"                                                              # mqtt客户端id
    mqtt_server_ip: "tcp://120.27.245.248:1883"                                             # mqtt 服务器ip
    mqtt_qs: 1                                                                              # mqtt 数据质量
    mqtt_topic_pre_fix: "ymzz/devices/YMZZ202500002/command"                                # mqtt 主题前缀
    mqtt_topic_init_pub_fix: "ymzz/devices/YMZZ202500002/data"                              # mqtt 发送数据前缀 -- 初始化上传数据
    mqtt_topic_device_pub_fix: "ymzz/devices/YMZZ202500002/status"                          # mqtt 发送数据前缀 -- 设备上传数据
    mqtt_topic_task_pub_fix: "ymzz/devices/YMZZ202500002/response"                          # mqtt 发送数据前缀 -- 任务上传数据
    mqtt_topic_alarm_sms_fix: "ymzz/devices/YMZZ202500002/response"                          # mqtt 发送数据前缀 -- 机器人报警短信上传
    mqtt_topic_request_task_fix: "ymzz/devices/YMZZ202500002/request_task"                          # mqtt 发送数据前缀 -- 机器人报警短信上传
    user_name: "ymzz_clent_h_0002"                                                                       # 用户名
    pass_word: "ymzz_clent_h_0002"                                                                       # 密码
    ca_cert: " "                                                                            # CA证书
    websocket_html_ip: "172.16.21.87"                                                       # websocket HTML IP
    websocket_html_port: 8000                                                               # websocket HTML 端口
    chassis_task_pub_name: "task_guidance/task"                                             # 底盘任务发布名称
    control_mode_pub_name: "control_mode"                                                   # 控制模式发布名称
    up_control_mode_pub_name: "up_control_mode"                                             # 上层控制模式发布名称
    current_robot_status_pub_name: "current_robot_status"                                   # 当前机器人状态发布名称
    led_show_pub_name: "cloud_chassis_led_show"
    chassis_task_status_sub_name: "task_guidance/task_states"                               # 底盘任务状态订阅名称
    data_update_list_sub_name: "data_list_update"                                           # 数据更新列表订阅名称
    power_threshold_parameter_update_sub_name: "cloud_chassis_power_charge_threshold"       # 电量阈值更新topic
    cloud_chassis_status_sub_name: "cloud_chassis_status_info"                              # 云迹底盘状态订阅topic
    up_limb_control_clinet_name: "up_climb_srv"                                             # 上肢控制服务名
    emoji_control_clinet_name: "emoji_service"                                              # 表情控制服务名
    audio_control_clinet_name: "audio_service"                                              # 音频控制服务名
    large_model_request_srv_name: "large_model_task_service"                                # 大型模型控制服务名
    mp3_file_path: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/audios.csv"                       # mp3文件路径
    expression_file_path: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/expression_list.csv"    # 表情文件路径
    up_action_file_path: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/up_action_list.csv"      # 上肢动作文件路径
    pose_file_path: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/mark_points.csv"              # 标定点文件路径
    service_wait_over_time: 5.0                                                             # ros2服务等待超时 5s
    http_time_out: 10000                                                                    # http超时时间
    control_move_heart_time: 2                                                              # 控制移动心跳时间
    low_battery_recharge_threshold: 20.0                                                    # 低电量充电阈值
    execute_task_battery_threshold: 80.0                                                    # 执行任务电量阈值
    node_task_status_sub_name: "node_task_states"                                           # 节点任务状态订阅名称
    is_enable_automatic_recharge: true                                                      # 是否启用自动充电

cloud_water_chassis_node:
  ros__parameters:
    server_address: "192.168.10.10"    #重定位action名称
    server_port: 31001
    mark_points_csv_adress: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/mark_points.csv"
    pub_chassis_status_info_topic: "cloud_chassis_status_info"
    cloud_water_mark_point_topic_name: "cloud_water_mark_point"
    cloud_water_move_base_topic: "cloud_cmd_vel"
    play_fixed_audio_pub_name: "play_fixed_audio"
    alarm_info_pub_name: "alarm_info"
    key_vel_move_base_topic: "key_cmd_vel"
    led_show_topic_name: "cloud_chassis_led_show"
    cloud_water_nav_target_srv_name: "cloud_water_nav_target"
    cloud_chassis_nav_action_name: "cloud_chassis_nav_action"
    cloud_chassis_charge_action_name: "cloud_chassis_charge_action"
    cloud_chassis_point_upadte_pub_name: "data_list_update"
    cloud_chassis_reposition_action_name: "cloud_chassis_reposition_action"
    max_linear_speed_sub_name: "cloud_chassis_max_linear_speed"
    max_angle_speed_sub_name: "cloud_chassis_max_angle_speed"
    cancel_current_move_sub_name: "cancel_current_task"
    max_continuous_retries: 3
    occupied_tolerance: 0.6
    traffic_peak_time_threshold: 8.0

audio_control_node:
  ros__parameters:
    modify_timbre_sub_name: "modify_timbre"
    audio_action_server_name: "audio_control_server"
    audio_control_action_name: "audio_control_action"
    service_wait_over_time: 5

set_params_action_node:
  ros__parameters:
    cloud_chassis_max_linear_speed_pub_name: "cloud_chassis_max_linear_speed"                              
    cloud_chassis_max_angular_speed_pub_name: "cloud_chassis_max_angle_speed"                        
    power_threshold_parameter_update_pub_name: "cloud_chassis_power_charge_threshold"  
    modify_timbre_pub_name: "modify_timbre"
    active_wake_up_threshold_pub_name: "active_wake_up_threshold"
    is_open_active_wake_up_name:  "is_open_active_wake_up"
    welcome_language_selection_name:  "welcome_word_update"
    is_open_near_point_explanation_pub_name:  "is_open_near_point_explanation"
    set_params_action_server_name: "set_params_server"
    mark_points_txt_adress: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/mark_points.csv"
    concession_distance_threshold_pub_name: "concession_distance_threshold"
    is_open_passive_wake_up_name: "is_open_passive_wake_up"
    yaml_file_adress: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/params/robot.yaml"
    modify_wakeup_word_pub_name: "modify_wakeup_word"

up_climb_action_node:
  ros__parameters:
    up_limb_srv_name: "up_climb_srv"
    up_climb_fixed_action_name: "up_climb_action"
    service_wait_over_time: 5

task_guidance:
  ros__parameters:
    cmd_vel_topic: "cmd_vel"                                    # 机器人速度话题
    task_topic: "task_guidance/task"                            # 任务话题
    task_states_feedback_topic: "task_guidance/task_states"     # 任务状态反馈话题
    is_used_tree: false                                         # 是否使用行为树   -- 好像没用到
    maps_dir: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/assets/maps"   # 地图文件目录路径
    slam_task_srv_name: "/pgo/pgo_map_slam"                     # SLAM建图
    save_pcd_srv_name: "/pgo/save_maps"                         # SLAM保存地图
    save_pgm_srv_name: "map_management/map_task_manage"         # PCD转PGM
    relocalizer_task_srv_name: "localizer/relocation_map_slam"  # SLAM重定位
    re_pcd_srv_name: "relocalize"                               
    timeout: 100 # milliseconds
    dot_point_update_topic: "task_guidance/dot_point_update"                             # 打点点位更新话题 -- 接收
    default_bt_xml_filename: "/home/ymrobot/ros2_ws_guidance/src/guided-robot/params/behavior_trees/cloud_bt.xml"  # 默认行为树
    cancel_current_task_pub_name: "cancel_current_task"
    plugin_lib_names:
      - say_something_node
      - need_index_node
      - parse_task_node
      - cloud_chassis_charge_node
      - cloud_chassis_nav_node
      - cloud_chassis_nav_name_node
      - set_params_node
      - remove_passed_mark_points_node
      - remove_passed_mark_audios_node
      - remove_passed_fixed_up_action_node
      - traverse_guidance_node
      - play_fixed_audio_node
      - up_climb_fixed_action_node
      # - pub_up_climb_stop_node #bug
      - get_standby_point_node #bug
      - voice_interaction
      - increment_variable_node
      - play_fulled_audio_node
      - video_camera_function_node
      - on_site_inspection_node
      - publish_task_state_node
      - remove_passed_is_skip_node
      - condition_check_node
                                      

